language: java
jdk: oraclejdk8
sudo: required

env:
  - DISPLAY=:99.0

before_install:
  - chmod +x CHANGELOG.md && chmod +x scripts/**
  - sh -e /etc/init.d/xvfb start

install:
  true

script:
  mvn clean package

after_success:
  - echo "Build successful. Awesome!"

after_failure:
  - echo "Build finished with errors. Bollocks!"

before_deploy:
  - VERSION=$(./scripts/get_version.sh)
  - BODY=$(./scripts/changelog_script.sh)

deploy:
  provider: releases
  api-key: $TOKEN
  body: "$BODY"
  tag-name: $VERSION
  name: "IOSMClient $VERSION"
  file_glob: true
  file: target/*.jar
  skip_cleanup: true
  on:
    branch: master
    repo: girtel/J-IOSMClient
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always


